micronaut:
  application:
    name: capivara
datasources:
  default:
    username: sa
    password: sa
    dialect: H2
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
curupira:
  reset: false
